server:
  port: 8080
logger:
  level: "debug"
  json: false
database:
  protocol: "mongodb"
  host: "localhost"
  port: 27017
  database: "qover"
  username: "usr"
  password: "P4ssw0rd!"
auth:
  domain: "https://auth.qover.com/"
  audience: "https://api.qover.com/"
  expiresAfterSeconds: 3600
  jwtSecret: "a-long-random-secret"
